{{- if .Values.createNamespace }}
{{- $ns := include "artstore.namespace" . }}
{{- if ne $ns .Release.Namespace }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $ns }}
  labels:
    {{- include "artstore.labels" . | nindent 4 }}
{{- end }}
{{- end }}
