# Кастомный образ Keycloak с темой Artstore
# Базовый образ: quay.io/keycloak/keycloak:26.1
# Тема копируется в /opt/keycloak/themes/artstore/
FROM quay.io/keycloak/keycloak:26.1

# Копируем кастомную тему Artstore
COPY themes/artstore /opt/keycloak/themes/artstore
