apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dc.fullname" . }}
  labels:
    {{- include "dc.labels" . | nindent 4 }}
type: Opaque
stringData:
  # --- OAuth / Token Manager ---
  DC_CLIENT_ID: {{ .Values.token.clientId | quote }}
  DC_CLIENT_SECRET: {{ .Values.token.clientSecret | quote }}
